test_netlist: LNA/LNA_Pooya.sp
parameter_list:
  - LNA-c1
  - LNA-c2
  - LNA-ld
  - LNA-lg
  - LNA-ls
  - LNA-wn1
  - LNA-wn2
performance_list:
  - LNA-Gt
  - LNA-s11
  - LNA-nf
  - LNA-bw
order:
  - 0
  - 3
  - 1
  - 2
sign:
  - 1
  - -1
  - -1
  - 1
arguments:
  model_path: config/model/45nm_CS.pm
  LNA-ls_start: 747p
  LNA-ls_stop: 754p
  LNA-ls_change: 1p
  LNA-ld_start: 3.7n
  LNA-ld_stop: 4.4n
  LNA-ld_change: 0.1n
  LNA-lg_start: 9.4n
  LNA-lg_stop: 10.8n
  LNA-lg_change: 0.2n
  LNA-w_start: 73u
  LNA-w_stop: 76.5u
  LNA-w_change: 0.5u
  out: data/LNA