parameter_list:
  - Wbias
  - Rd
  - Wn1
  - Wn2
performance_list:
  - Bandwidth
  - Power Consumption
  - Voltage Gain
order:
  - 0
  - 2
  - 1
sign:
  - 1
  - -1
  - 1
arguments:
  input: data/Cascode
  out: data/Cascode