parameter_list:
  - Cascode-wbias
  - Cascode-r
  - Cascode-w0
  - Cascode-w1
performance_list:
  - Cascode-bw
  - Cascode-pw
  - Cascode-a0
order:
  - 0
  - 2
  - 1
sign:
  - 1
  - -1
  - 1
arguments:
  out: data/Cascode