parameter_list:
  - C1
  - C2
  - Ld
  - Lg
  - Ls
  - WN1
  - WN2
performance_list:
  - GT
  - S11
  - NF
  - Bandwidth
  - Power Consumption
order:
  - 1
  - 3
  - 0
  - 2
  - 4
sign:
  - 1
  - -1
  - -1
  - 1
  - -1
arguments:
  input: data/LNA
  out: data/LNA