parameter_list:
  - LNA-c1
  - LNA-c2
  - LNA-ld
  - LNA-lg
  - LNA-ls
  - LNA-wn1
  - LNA-wn2
performance_list:
  - LNA-Gt
  - LNA-s11
  - LNA-nf
  - LNA-bw
order:
  - 0
  - 3
  - 1
  - 2
sign:
  - 1
  - -1
  - -1
  - 1
arguments:
  out: data/LNA