parameter_list:
  - Mixer-vbrf
  - Mixer-rl
  - Mixer-wn
  - Mixer-wt
performance_list:
  - Mixer-PowerConsumption
  - Mixer-Swing
  - Mixer-Conversion_Gain
order:
  - 0
  - 2
  - 1
sign:
  - -1
  - 1
  - 1
arguments:
  out: data/Mixer