parameter_list:
  - PA-l1p
  - PA-l1s
  - PA-l3p
  - PA-l3s
  - PA-lm
  - PA-wn1
  - PA-wn2
performance_list:
  - PA-S11
  - PA-S22
  - PA-largesignalpg
  - PA-PAE
  - PA-DE
  - PA-PSAT
  - PA-pw
order:
  - 5
  - 6
  - 0
  - 1
  - 2
  - 3
  - 4
sign:
  - -1
  - -1
  - 1
  - 1
  - 1
  - 1
  - -1
arguments:
  out: data/PA



