parameter_list:
  - C1_LNA
  - C2_LNA
  - Ld_LNA
  - Lg_LNA
  - Ls_LNA
  - WN1_LNA
  - WN2_LNA
  - C_Mixer
  - R_Mixer
  - WLO_Mixer
  - WRF_Mixer
  - Rd_Amp
  - Wn1_Amp
  - Wn2_Amp
performance_list:
  - dcPowerConsumption_System
  - VoltageGain_System_Value
  - NoiseFigure_System_Value
  - PowerGain_LNA/dB
  - NoiseFigure_LNA/dB
  - S11_LNA/dB
  - ConversionGain_Mixer/dB
  - VoltageSwing_Mixer/V
  - VoltageGain_Amp/dB
order: 
  - 2
  - 1
  - 0
  - 5
  - 3
  - 4
  - 6
  - 7
  - 8
sign:
  - -1
  - 1
  - -1
  - 1
  - -1
  - -1
  - 1
  - 1
  - 1
arguments:
  input: data/Receiver
  out: data/Receiver