parameter_list:
  - C_Mixer
  - R_Mixer
  - WLO_Mixer
  - WRF_Mixer
performance_list:
  - ConversionGain_Mixer/dB
  - VoltageSwing_Mixer/V
order: 
  - 0
  - 1
sign:
  - 1
  - 1
arguments:
  input: data/Receiver-Mixer
  out: data/Receiver-Mixer