parameter_list:
  - C1_LNA
  - C2_LNA
  - Ld_LNA
  - Lg_LNA
  - Ls_LNA
  - WN1_LNA
  - WN2_LNA
performance_list:
  - PowerGain_LNA/dB
  - NoiseFigure_LNA/dB
  - S11_LNA/dB
order: 
  - 2
  - 0
  - 1
sign:
  - 1
  - -1
  - -1
arguments:
  input: data/Receiver-LNA
  out: data/Receiver-LNA