parameter_list:
  - C_Mixer
  - R_Mixer
  - WLO_Mixer
  - WRF_Mixer
performance_list:
  - ConversionGain_Mixer/dB
  - VoltageSwing_Mixer/V
arguments:
  input: data/Receiver-Mixer
  out: data/Receiver-Mixer