parameter_list:
  - VDD
  - Vgate
  - Wn
  - Rd
performance_list:
  - Bandwidth
  - Power Consumption
  - Voltage Gain
order:
  - 0
  - 2
  - 1
sign:
  - 1
  - -1
  - 1
arguments:
  input: data/SingleStageAmplifier
  out: data/SingleStageAmplifier