parameter_list:
  - C1_VCO
  - L1_VCO
  - Rp_VCO
  - Wn_VCO
  - Wn6_VCO
  - Wvar_VCO
  - L1p_PA
  - L1s_PA
  - L3p_PA
  - L3s_PA
  - Wn1_PA
  - Wn2_PA
performance_list:
  - dcPowerConsumption/W
  - 3dB_Bandwidth/Hz
  - OutputPower/dBm
  - VoltageSwing/V
  - TuningRange_VCO/Hz
  - PhaseNoise_VCO/(dBc/Hz)
  - LargeSignal_PowerGain_PA/dB
  - DrainEfficiency_PA/%
  - PAE_PA/%
arguments:
  input: data/Transmitter
  out: data/Transmitter