parameter_list:
  - L1p_PA
  - L1s_PA
  - L3p_PA
  - L3s_PA
  - Wn1_PA
  - Wn2_PA
performance_list:
  - dcPowerConsumption/W
  - 3dB_Bandwidth/Hz
  - OutputPower/dBm
  - VoltageSwing/V
  - LargeSignal_PowerGain_PA/dB
  - DrainEfficiency/%
  - PAE/%
order:
  - 3
  - 6
  - 4
  - 5
  - 0
  - 1
  - 2
sign:
  - -1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
arguments:
  input: data/Transmitter-PA
  out: data/Transmitter-PA