parameter_list:
  - L1p_PA
  - L1s_PA
  - L3p_PA
  - L3s_PA
  - Wn1_PA
  - Wn2_PA
performance_list:
  - LargeSignal_PowerGain_PA/dB
  - DrainEfficiency/%
  - PAE/%
order:
  - 0
  - 1
  - 2
sign:
  - 1
  - 1
  - 1
arguments:
  input: data/Transmitter-PA
  out: data/Transmitter-PA