parameter_list:
  - C1_VCO
  - L1_VCO
  - Rp_VCO
  - Wn_VCO
  - Wn6_VCO
  - Wvar_VCO
performance_list:
  - TuningRange_VCO/Hz
  - PhaseNoise_VCO/(dBc/Hz)
order:
  - 0
  - 1
sign:
  - 1
  - -1
arguments:
  input: data/Transmitter-VCO
  out: data/Transmitter-VCO