parameter_list:
  - C1_VCO
  - L1_VCO
  - Rp_VCO
  - Wn_VCO
  - Wn6_VCO
  - Wvar_VCO
performance_list:
  - dcPowerConsumption/W
  - 3dB_Bandwidth/Hz
  - OutputPower/dBm
  - VoltageSwing/V
  - TuningRange_VCO/Hz
  - PhaseNoise_VCO/(dBc/Hz)
order:
  - 2
  - 5
  - 3
  - 4
  - 0
  - 1
sign:
  - -1
  - 1
  - 1
  - 1
  - 1
  - -1
arguments:
  input: data/Transmitter-VCO
  out: data/Transmitter-VCO