parameter_list:
  - C1
  - WNOUT
  - WPOUT
  - WCS
  - WN1
  - WP1
performance_list:
  - Bandwidth
  - Power Consumption
  - Voltage Gain
arguments:
  input: data/TwoStageAmplifier
  out: data/TwoStageAmplifier