parameter_list:
  - vco-c1
  - vco-l1
  - vco-rp
  - vco-wn
  - vco-wn5
  - vco-wn6
  - vco-wvar
performance_list:
  - vco-oscilationfreq
  - vco-pw
  - vco-outputpower
  - vco-phasenoise
  - vco-tuningrange
order: 
  - 0
  - 1
  - 2
  - 3
  - 4
sign:
  - 1
  - -1
  - 1
  - -1
  - 1
arguments:
  out: data/VCO