parameter_list:
  - vco-wn
  - vco-wt
  - vco-wv
  - vco-lt
performance_list:
  - vco-power_consumption
  - vco-out_power
  - vco-tuningrange
order:
  - 0
  - 1
  - 2
sign:
  - -1
  - 1
  - 1
arguments:
  out: data/VCO

  