parameter_list:
  - C1
  - L1
  - Rp
  - Wn
  - Wn5
  - Wn6
  - Wvar
performance_list:
  - Oscillation Frequency
  - Power Consumption
  - Output Power
  - Phase Noise
  - Tuning Range
arguments:
  input: Dataset/VCO
  out: Dataset/VCO