parameter_list:
  - C1
  - L1
  - Rp
  - Wn
  - Wn5
  - Wn6
  - Wvar
performance_list:
  - Oscillation Frequency
  - Power Consumption
  - Output Power
  - Phase Noise
  - Tuning Range
order: 
  - 0
  - 1
  - 2
  - 3
  - 4
sign:
  - 1
  - -1
  - 1
  - -1
  - 1
arguments:
  input: data/VCO
  out: data/VCO