dataset:
  - type: Base
model_config:
  - model: SupportVectorRegressor
metric: absolute
rerun_training: False
device: cpu
check_circuit: False
num_sample_check: 8
random_sample_scale: 1.5
log_experiments: False
epsilon: 0.3
subset:
  - 0.9
circuits:
  - LNA
compare_dataset: False
compare_method: False
subset_percentage: 0.3
mode: replace
subset_parameter_check: False
independent_sample: True
test_accuracy_per_epoch: False
test_margin_accuracy: False