parameter_list:
  - Mixer-c
  - Mixer-r
  - Mixer-wlo  
  - Mixer-wrf
performance_list:
  - Mixer-pw
  - Mixer-swing
  - Mixer-conversiongain
  - Mixer-noisefigure
order:
  - 0
  - 3
  - 1
  - 2
sign:
  - -1
  - 1
  - 1
  - -1
arguments:
  out: data/Mixer