parameter_list:
  - VCO-c1
  - VCO-l1
  - VCO-rp
  - VCO-wn
  - VCO-wn6
  - VCO-wvar
performance_list:
  - VCO-dcPowerConsumption/W
  - VCO-3dB_Bandwidth/Hz
  - VCO-OutputPower/dBm
  - VCO-VoltageSwing/V
  - VCO-TuningRange
  - VCO-PhaseNoise
order:
  - 2
  - 5
  - 3
  - 4
  - 0
  - 1
sign:
  - -1
  - 1
  - 1
  - 1
  - 1
  - -1
arguments:
  out: data/Transmitter-VCO



